PPI2/PPI2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('usuarios/', include('django.contrib.auth.urls')),
    path('perguntas/', include('questions_and_answers.urls')),
    path('horarios/', include('timetable.urls')),
    path('', include('timetable.urls')),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path(
        'accounts/logout/', views.LogoutView.as_view(next_page='/'),
        name='logout'
    ),    
]

PPI2/timetable/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views
from . import models
from django.views.generic import TemplateView
from questions_and_answers import urls


urlpatterns = [
    path('', views.cursos, name='home'),
    path('cursos/', views.cursos, name='cursos'),
    path(
        'unidades_curriculares', views.unidades_curriculares,
        name='unidades_curriculares'
    ),
    path('horarios/', include('django.contrib.auth.urls')),
    path('perguntas/', include('questions_and_answers.urls')),
    path('cursos/<pk>/deleta_curso', views.deleta_curso, name='deleta_curso'),
    path('cursos/<pk>/deleta_curso_confirmacao', views.deleta_curso_confirmacao,
        name='deleta_curso_confirmacao'),
    path('cursos/<pk>/edita_curso', views.edita_curso, name='edita_curso'),
    path('contato/', views.contato, name='contato'),
    path('contato/obg', views.obg, name='obg'),
    path('professores', views.professores, name='professores'),
    path('professores/<pk>/deleta_professor_confirmacao',
        views.deleta_professor_confirmacao,name='deleta_professor_confirmacao'),
    path('professores/<pk>/deleta_professor', views.deleta_professor,
        name='deleta_professor'),
    path('professores/<pk>/edita_professor', views.editar_professor,
        name='editar_professor'),
    path('unidades_curriculares/<pk>/deleta_unidade_curricular_confirmacao',
        views.deleta_uc_confirmacao, name='deleta_uc_confirmacao'),
    path('unidades_curriculares/<pk>/deleta_unidade_curricular',
        views.deleta_uc, name='deleta_uc'),
    path('unidades_curriculares/<pk>/edita_unidade_curricular',
        views.editar_uc, name='editar_unidade_curricular'),
    path('registrar_usuario/', models.registrar_usuario.as_view(),
        name="registrar_usuario"),
    path('valida_usuario/', views.valida_usuario, name="valida_usuario"),
    path('reseta_senha/', views.password, name="reseta_senha"),
]

PPI2/timetable/models.py
from django.db import models
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
#https://docs.djangoproject.com/en/2.2/ref/models/fields/#model-field-types

class Professor(models.Model):
    nome = models.CharField(max_length = 50)

    def __str__(self):
        return self.nome

class Curso(models.Model):

    MATUTINO = 'Matutino'
    VESPERTINO = 'Vespertino'
    NOTURNO = 'Noturno'
    INTEGRAL = 'Integral'
    OPCOES_TURNO = (
        (MATUTINO, 'Matutino'),
        (VESPERTINO, 'Vespertino'),
        (NOTURNO, 'Noturno'),
        (INTEGRAL, 'Integral'),
    )

    nome = models.CharField(max_length = 100)
    quantidade_de_modulos = models.IntegerField()
    coordenador = models.ForeignKey(
        'Professor', on_delete = models.SET_NULL, null = True
    )
    # coordenador = models.CharField(max_length = 100, null=True)
    turno = models.CharField(
        max_length = 10, choices = OPCOES_TURNO, default = 'Matutino',
    )

    def __str__(self):
        return self.nome

class UnidadeCurricular(models.Model):
    SEGUNDA_FEIRA = '2'
    TERCA_FEIRA = '3'
    QUARTA_FEIRA = '4'
    QUINTA_FEIRA = '5'
    SEXTA_FEIRA = '6'

    DIAS_DA_SEMANA = (
        (SEGUNDA_FEIRA, 'Segunda-feira'),
        (TERCA_FEIRA, 'Terça-feira'),
        (QUARTA_FEIRA, 'Quarta-feira'),
        (QUINTA_FEIRA, 'Quinta-feira'),
        (SEXTA_FEIRA, 'Sexta-feira'),
    )
    dias_das_aulas = models.CharField(
        max_length = 25,
        choices = DIAS_DA_SEMANA,
        default = 'Segunda-feira',
    )
    nome = models.CharField(max_length = 100)
    carga_horaria = models.IntegerField()
    sala = models.CharField(max_length = 50)
    modulo = models.IntegerField()
    horario_de_inicio = models.TimeField()
    horario_de_termino = models.TimeField()
    professor = models.ForeignKey('Professor', on_delete = models.SET_NULL,
    null = True)
    curso = models.ForeignKey('Curso', on_delete = models.SET_NULL,
    null = True)

    def __str__(self):
        return self.nome

    def horarioInicioToString(self):
        return str(self.horario_de_inicio)

class registrar_usuario(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('accounts/login')
    template_name = 'registration/registrar_usuario.html'

PPI2/timetable/forms.py
from django import forms
from django.forms import ModelForm, Textarea, TextInput, NumberInput, Select, \
TimeInput, CheckboxInput, SelectMultiple
from .models import Curso, UnidadeCurricular, Professor
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column

class FormCurso(forms.ModelForm):

    class Meta:
        model = Curso
        fields = ('nome', 'quantidade_de_modulos', 'coordenador', 'turno')

        widgets = {
            'nome': TextInput(attrs={'class': 'mdl-textfield__input'}),
            'coordenador': Select(attrs={'class': 'mdl-textfield__input'}),
            'quantidade_de_modulos':  TextInput(attrs={'class': 'mdl-textfield__input',
            'pattern': '-?[0-9]*(\.[0-9]+)?'}),
            'turno': Select(attrs={'class': 'mdl-textfield__input'}),
        }

class FormProfessor(forms.ModelForm):

    class Meta:
        model = Professor
        fields = ('nome', )
        widgets = {
            'nome': TextInput(attrs={'class': 'mdl-textfield__input'}),
        }

class FormUnidadeCurricular(forms.ModelForm):

    class Meta:
        model = UnidadeCurricular

        fields = (
            'nome', 'carga_horaria', 'sala', 'modulo', 'horario_de_inicio',
            'horario_de_termino', 'professor', 'curso', 'dias_das_aulas',
        )

        widgets = {
            'nome': TextInput(attrs={'class': 'mdl-textfield__input'}),
            'carga_horaria': TextInput(attrs={'class': 'mdl-textfield__input'}),
            'sala': TextInput(attrs={'class': 'mdl-textfield__input'}),
            'modulo': TextInput(attrs={'class': 'mdl-textfield__input'}),
            'horario_de_inicio': TimeInput(attrs={'class': 'mdl-textfield__input',
            'type': 'time'}),
            'horario_de_termino': TimeInput(attrs={'class': 'mdl-textfield__input',
            'type': 'time'}),
            # 'dias_das_aulas': Select(
            #     attrs={'id': 'id_dias_das_aulas'}
            # ),
            'professor': Select(attrs={'class': 'mdl-textfield__input'}),
            'curso': Select(attrs={'class': 'mdl-textfield__input'}),
        }

class ContatoForm(forms.Form):
    emissor = forms.EmailField(required=True, label='Remetente')
    assunto = forms.CharField(required=True)
    msg = forms.CharField(widget=forms.Textarea, label='Mensagem')


    def __init__(self, *args, **kwargs):
        super(ContatoForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            Row(
                Column('emissor', css_class='form-group col-md-6'),
                Column('assunto', css_class='form-group col-md-6'),
                css_class='form-row'
            ),
            'msg'
        )
        self.helper.add_input(Submit('submit', 'Enviar'))
        # self.helper.add_input(Reset('reset', 'Limpar', css_class='btn-danger float-right'))

PPI2/timetable/views.py
from .forms import FormCurso, FormUnidadeCurricular, FormProfessor, ContatoForm
from .models import Curso, Professor, UnidadeCurricular
from django.urls import reverse_lazy
from django.views import generic
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import send_mail, BadHeaderError
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
import pdb

# Create your views here.
def home(request):
    return render(request, 'timetable/home.html')

@login_required
def cursos(request):
    lista_cursos = Curso.objects.all()
    uc_por_curso = {}
    for curso in lista_cursos:
        uc_por_curso[curso.nome] = UnidadeCurricular.objects.filter(
            curso_id = Curso.objects.get(nome = curso.nome).id
        )

    if request.method == 'POST':
        form = FormCurso(request.POST)
        if form.is_valid():
            form.save()
            return redirect('cursos')
        else:
            return redirect('home')
    else:
        form = FormCurso()
        # pdb.set_trace()
    string_dias = ""
    for num in range(2, 7):
        string_dias += str(num)
    return render(
        request, 'timetable/cursos.html', {'form': form,
        'lista_cursos': lista_cursos, 'uc_por_curso': uc_por_curso,
        'range': string_dias}
    )

@login_required
def unidades_curriculares(request):
    lista_unidades_curriculares = UnidadeCurricular.objects.all()

    if request.method == 'POST':
        form = FormUnidadeCurricular(request.POST)
        if form.is_valid():
            nova_uc = form.save(commit=False)
            nova_uc.dias_das_aulas = ''
            for dia in request.POST.getlist('dias_das_aulas'):
                nova_uc.dias_das_aulas += dia
            nova_uc.horario_de_inicio = str(nova_uc.horario_de_inicio)
            nova_uc.horario_de_termino = str(nova_uc.horario_de_termino)
            nova_uc.save()
            # pdb.set_trace()
            return redirect('unidades_curriculares')
        else:
             pdb.set_trace()
            # return redirect('FORM_NOT_VALID')
    else:
        form = FormUnidadeCurricular()
        # pdb.set_trace()
    return render(
        request, 'timetable/unidades_curriculares.html', {'form': form,
        'lista_unidades_curriculares': lista_unidades_curriculares}
    )

def deleta_curso(request, pk):
    curso = get_object_or_404(Curso, pk=pk)
    curso.delete()
    return redirect('cursos')

def edita_curso(request, pk):
    curso = get_object_or_404(Curso, pk=pk)
    if request.method == "POST":
        form = FormCurso(request.POST, instance=curso)
        if form.is_valid():
            curso = form.save()
            return redirect('cursos')
    else:
        # return render(request, 'timetable/edita_curso.html', {'curso': curso})
        form = FormCurso(instance=curso)
    return render(request, 'timetable/edita_curso.html', {'form': form})

def contato(request):
    if request.method == 'GET':
        email_form = ContatoForm()
    else:
        email_form = ContatoForm(request.POST)
        if email_form.is_valid():
            emissor = email_form.cleaned_data['emissor']
            assunto = email_form.cleaned_data['assunto']
            msg = email_form.cleaned_data['msg']

            try:
                send_mail(assunto, msg, emissor, ['wille.diegoricardo@gmail.com'])
                messages.success(request, 'Mensagem enviada!',
                    extra_tags='alert')
                return redirect('contato')
            except BadHeaderError:
                messages.error(request, 'Erro ao enviar mensagem.',
                extra_tags='alert-danger')
                return HttpResponse("Erro =/")
            # return redirect('obg')
    return render(request, 'timetable/contato.html', {'form': email_form})

def obg(request):
    return HttpResponse("<h2>Obrigado pela mensagem!!!</h2>")

def deleta_curso_confirmacao(request, pk):
    curso = get_object_or_404(Curso, pk=pk)
    return render(request, 'timetable/excluir_curso.html', {'curso': curso})

def deleta_professor_confirmacao(request, pk):
    professor = get_object_or_404(Professor, pk=pk)
    return render(request, 'timetable/excluir_professor.html',
        {'professor': professor})

def deleta_professor(request, pk):
    professor = get_object_or_404(Professor, pk=pk)
    professor.delete()
    return redirect('professores')

def professores(request):
    professores = Professor.objects.all()
    lista_cursos = Curso.objects.all()
    lista_unidades_curriculares = UnidadeCurricular.objects.all()

    if request.method == 'POST':
        form = FormProfessor(request.POST)
        if form.is_valid():
            form.save()
            return redirect('professores')
        else:
            return HttpResponse("<h2>Else error</h2>")
    else:
        form = FormCurso()
    return render(request, 'timetable/professores.html',
        {'professores': professores, 'form': form, 'lista_cursos': lista_cursos,
        'lista_unidades_curriculares': lista_unidades_curriculares})

def editar_professor(request, pk):
    professor = get_object_or_404(Professor, pk=pk)
    if request.method == "POST":
        form = FormProfessor(request.POST, instance=professor)
        if form.is_valid():
            curso = form.save()
            return redirect('professores')
    else:
        form = FormProfessor(instance=professor)
    return render(request, 'timetable/editar_professor.html', {'form': form})

def editar_uc(request, pk):
    unidade_curricular = get_object_or_404(UnidadeCurricular, pk=pk)
    if request.method == "POST":
        form = FormUnidadeCurricular(request.POST, instance=unidade_curricular)
        if form.is_valid():
            unidade_curricular.dias_das_aulas = ''
            for dia in request.POST.getlist('dias_das_aulas'):
                unidade_curricular.dias_das_aulas += dia
            unidade_curricular = form.save()
            return redirect('unidades_curriculares')
    else:
        form = FormUnidadeCurricular(instance=unidade_curricular)
    # pdb.set_trace()
    return render(request, 'timetable/editar_uc.html', {'form': form,
        'dias_das_aulas': unidade_curricular.dias_das_aulas})

def deleta_uc_confirmacao(request, pk):
    unidade_curricular = get_object_or_404(UnidadeCurricular, pk=pk)
    return render(request, 'timetable/excluir_unidade_curricular.html',
        {'unidade_curricular': unidade_curricular})

def deleta_uc(request, pk):
    unidade_curricular = get_object_or_404(UnidadeCurricular, pk=pk)
    unidade_curricular.delete()
    return redirect('unidades_curriculares')

# class registrar_usuario(generic.CreateView):
#     form_class = UserCreationForm
#     success_url = reverse_lazy('accounts/login')
#     template_name = 'registration/registrar_usuario.html'

def valida_usuario(request):
    usuario = request.GET.get('usuario', None)
    dados = {
        'usuario': usuario,
        'em_uso': User.objects.filter(username=usuario).exists()
    }
    return JsonResponse(dados)

@login_required
def password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Senha atualizada com sucesso!',
                extra_tags='alert')
            return redirect('reseta_senha')
        else:
            messages.error(request, 'Corrija os erros', extra_tags='alert')
    else:
        form = PasswordChangeForm(request.user)
    return render(
        request, 'registration/change_password.html', {'form': form}
    )

PPI2/templates/timetable/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br" dir="ltr">
  <head>
    <!-- <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'javascript/bootstrap.min.js' %}"></script> -->
    <link rel="stylesheet"
      href="{% static 'css/material.min.css' %}" />
    <script src="{% static 'javascript/material.min.js' %}"></script>
    <script src="{% static 'javascript/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'javascript/global_timetable.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/timetable.css' %}">
    <link rel="stylesheet"
      href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    {% block head %}
    {% endblock %}
    <title>Horários</title>
  </head>
  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <header class="mdl-layout__header">
        <div class="mdl-layout-icon">
          <a href="#">
            <i class="material-icons">menu</i>
          </a>
        </div>
        <div class="mdl-layout__header-row">
          {% block header %}{% endblock %}
          <!-- <div class="mdl-layout-spacer"></div> -->
          {% if user.is_anonymous %}
            <button id="login_button" class="mdl-button mdl-js-button
            mdl-js-ripple-effect mdl-button--raised"
            onclick="document.getElementById('login_modal').style.display='block'">
              Login
            </button>
          {% endif %}
          {% if user.is_authenticated %}
            <span class="mdl-chip">
              <span class="mdl-chip__contact mdl-color--teal mdl-color-text--white">
                {{ user.username.0 }}
              </span>
              <span class="mdl-chip__text">{{ user.username }}
                <!-- <small>(<a href="{% url 'logout' %}">Sair</a>)
                </small> -->
                <button type="button" class="mdl-chip__action" id="user_actions">
                  <i class="material-icons">
                    arrow_drop_down
                  </i>
                </button>
                <ul class="mdl-menu mdl-js-menu mdl-menu--bottom-right mdl-js-ripple-effect"
                  for="user_actions">
                  <a href="{% url 'logout' %}">
                    <li class="mdl-menu__item">Sair</li>
                  </a>
                  <a href="{% url 'reseta_senha' %}">
                    <li class="mdl-menu__item">Alterar senha</li>
                  </a>
                </ul>
              </span>
            </span>
          {% endif %}
        </div>
        {% block tabs_cursos %}{% endblock %}
      </header>
      <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">Horários</span>
        <nav class="mdl-navigation">
         <div class="mdl-layout--small-screen-only">
           <a class="mdl-navigation__link" href="{% url 'login' %}">
             Login
           </a>
         </div>
         <a href="{% url 'home' %}" class="mdl-navigation__link">Início</a>
         <a href="{% url 'cursos' %}" class="mdl-navigation__link">Cursos</a>
         <a href="{% url 'professores' %}" class="mdl-navigation__link">
           Professores
         </a>
         <a href="{% url 'unidades_curriculares' %}" class="mdl-navigation__link">
           Unidades Curriculares
         </a>
         <a href="/perguntas" class="mdl-navigation__link">
           Perguntas e Respostas
         </a>
        </nav>
      </div>
      <main class="mdl-layout__content">
        {% block conteudo %}{% endblock %}
      </main>
      {% block form %}{% endblock %}
      <footer class="mdl-mini-footer">
        <div class="mdl-mini-footer__left-section">
          <div class="mdl-logo">
            <img src="{% static "images/canoinhas_vertical_marca.png" %}" alt="">
          </div>
        </div>
        <div class="mdl-mini-footer__middle-section">
          Instituto Federal de Santa Catarina<br />Campus Canoinhas
          <br />Av. Expedicionários, 2150 - Bairro Campo da Água Verde<br />
          CEP 89466-312
        </div>
        <div class="mdl-mini-footer__right-section">
          <div class="mdl-tooltip mdl-tooltip--large" data-mdl-for="yt">
            IFSC TV
          </div>
          <a class="mdl-navigation__link" id="yt"
          href="https://www.youtube.com/user/ifsccomunicacao" target="_blank">
            <div class="mdl-mini-footer__social-btn">
              <img src="{% static "images/youtube_social_squircle_red.png" %}"
              alt="Youtube logo. Link para IFSC TV">
            </div>
          </a>
          <div class="mdl-tooltip mdl-tooltip--large" data-mdl-for="contato">
            Entre em contato
          </div>
          <a class="mdl-navigation__link" href="{% url 'contato' %}"
            target="_blank" id="contato">
            <i class="material-icons">
              contact_mail
            </i>
          </a>
        </div>
      </footer>
    </div>
    <div id="login_modal" class="login_modal">
      <form class="login_form" method="post" action="{% url 'login' %}">
        {% csrf_token %}
           <div class="container login_modal_content">
             <div class="close-container">
               <span onclick="document.getElementById('login_modal').style.display='none'"
               class="close">
                 &times;
               </span>
             </div>
             <div class="modal_header">
               <h2 class="mdl-dialog__title">Entrar</h2>
             </div>
             <div class="mdl-textfield mdl-js-textfield">
               <label class="mdl-textfield__label" for="id_username">Usuário</label>
               <input class="mdl-textfield__input" id="id_username" type="text"
               name="username" />
             </div>
             <br />
             <div class="mdl-textfield mdl-js-textfield">
               <label class="mdl-textfield__label" for="{{  form.password.name }}">
                 Senha
               </label>
               <input class="mdl-textfield__input" id="id_{{ form.password.name }}"
               type="password" name="password" />
             </div>
             <br />
             <button class="mdl-button mdl-js-button
             mdl-js-ripple-effect mdl-button--raised login_button" type="submit">
             Login
             </button>
             <div>
               <span>Esqueceu a <a href="{% url 'password_reset' %}">senha?</a></span><br />
               <span>Não possui uma conta? <a href="{% url 'signup' %}">Criar nova conta</a></span>
             </div>
           </div>
      </form>
      <script src=" {% static 'javascript/login_modal_exit.js' %}">
      </script>
    </div>
    {% block script %}
    {% endblock %}
  </body>
</html>

PPI2/templates/timetable/contato.html
{% extends 'timetable/base.html' %}

<!-- {% load crispy_forms_tags %} -->

{% block header %}
  <span class="mdl-layout__title">Contato</span>
  <div class="mdl-layout-spacer"></div>
{% endblock %}

{% block conteudo %}
  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li class="{{ message.tags }}">
          {{ message }}<span class="close-alert">&times;</span>
        </li>
      {% endfor %}
    </ul>
  {% endif %}
  {% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}
        <div class="alert-danger">
          <strong>{{ error|escape }}</strong>
          <span class="close-alert">&times;</span>
        </div>
      {% endfor %}
      {% for error in form.non_field_errors %}
        <div class="alert-danger">
          <strong> {{ error|escape }}</strong>
          <span class="close-alert">&times;</span>
        </div>
      {% endfor %}
    {% endfor %}
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      <label class="mdl-textfield__label" for="id_emissor">
        Remetente
      </label>
      <input class="mdl-textfield__input" type="email" name="emissor"
        id="id_emissor" required>
    </div>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      <label class="mdl-textfield__label" for="id_assunto">
        Assunto
      </label>
      <input class="mdl-textfield__input" type="text" name="assunto"
        id="id_assunto" required>
    </div>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      <label class="mdl-textfield__label" for="id_msg">
        Mensagem
      </label>
      <textarea class="mdl-textfield__input" type="text" name="msg"
        id="id_msg" rows="10" cols="40" required></textarea>
    </div>
    <button type="submit" name="submit" class="mdl-button mdl-js-button
      mdl-button--raised mdl-js-ripple-effect mdl-button--accent"
      id="contato_button">
      Enviar
    </button>
  </form>
  <!-- {% crispy form  %} -->
{% endblock %}

PPI2/templates/timetable/edita_curso.html
{% extends "timetable/base.html" %}

{% block header %}
  <span class="mdl-layout__title">Editar Curso</span>
  <div class="mdl-layout-spacer"></div>
{% endblock %}

{% block conteudo %}
<!-- <form method="post">
  {% csrf_token %}
  <div class="mdl-textfield mdl-js-textfield">
    <input class="mdl-textfield__input" type="text" value="{{ curso.nome }}"
    id="nome_curso" required>
    <label class="mdl-textfield__label" for="nome_curso">Nome do Curso</label>
  </div>
  <div class="mdl-textfield mdl-js-textfield">
    <input class="mdl-textfield__input" type="text" value="{{ curso.coordenador }}"
    id="nome_coordenador" required>
    <label class="mdl-textfield__label" for="nome_coordenador">Nome do coordenador</label>
  </div>
  <div class="mdl-textfield mdl-js-textfield">
    <input class="mdl-textfield__input" type="text" value="{{ curso.quantidade_de_modulos }}"
    id="quantidade_de_modulos" required>
    <label class="mdl-textfield__label" for="quantidade_de_modulos">Quantidade de módulos</label>
  </div>
  <div class="mdl-textfield mdl-js-textfield">
    <input class="mdl-textfield__input" type="text" value="{{ curso.turno }}"
    id="turno" required>
    <label class="mdl-textfield__label" for="turno">Turno</label>
  </div>
</form> -->
<form method="post">
  {% csrf_token %}
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <label class="mdl-textfield__label" for="id_{{ form.nome.name }}">
      Nome
    </label>
    {{ form.nome }}
  </div>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <label class="mdl-textfield__label" for="id_{{ form.coordenador.name }}">
      Coordenador
    </label>
    <br />
    {{ form.coordenador }}
  </div>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <label class="mdl-textfield__label"
    for="id_{{ form.quantidade_de_modulos.name }}">
      Quantidade de módulos
    </label>
    {{ form.quantidade_de_modulos }}
  </div>
  <div class="mdl-textfield mdl-js-textfield getmdl-select
    mdl-textfield--floating-label">
    <label class="mdl-textfield__label" for="id_{{ form.turno.name }}">
    </label>
    {{ form.turno }}
  </div>
  <button class="mdl-button mdl-js-button mdl-button--raised
    mdl-textfield--floating-label mdl-js-ripple-effect mdl-button--accent"
    id="modal_enviar" type="submit">
    Editar
  </button>
</form>
{% endblock %}

PPI2/templates/timetable/editar_professor.html
{% extends "timetable/base.html" %}

{% block header %}
  <span class="mdl-layout__title">Editar Professor</span>
  <div class="mdl-layout-spacer"></div>
{% endblock %}

{% block conteudo %}
<form method="post">
  {% csrf_token %}
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <label class="mdl-textfield__label" for="id_{{ form.nome.name }}">
      Nome
    </label>
    {{ form.nome }}
  </div>
  <button class="mdl-button mdl-js-button mdl-button--raised
  mdl-js-ripple-effect mdl-button--accent" id="modal_enviar"
  type="submit">
    Editar
  </button>
</form>
{% endblock %}

PPI2/templates/timetable/home.html
{% extends 'timetable/base.html' %}

{% block header %}
  <span class="mdl-layout__title">Horários</span>
{% endblock %}

{% block conteudo %}  
{% endblock %}